services:
  app:
    image: spokanetech:latest
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    image: spokanetech:latest
    build:
      context: .
    container_name: worker
    ports:
      - "5555:5555"
    env_file:
      - .env

  redis:
    image: redis:7.2
    container_name: redis
    ports:
     - "6379:6379"
