services:
  app:
    image: spokanetech:latest
    build:
      context: .
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env

  worker:
    image: spokanetech:latest
    build:
      context: .
    command: [
      "python",
      "-m",
      "celery",
      "--workdir",
      "./src",
      "-A",
      "spokanetech.celery",
      "worker",
      "-B",
      "-l",
      "INFO",
      "--events"
    ]
    container_name: worker
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      SPOKANE_TECH_DEV: false
      CELERY_BROKER_URL: "redis://redis:6379/0"

  redis:
    image: redis:7.2
    container_name: redis
    ports:
     - "6379:6379"
