# Generated by Django 5.0.1 on 2024-01-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of this event', max_length=64)),
                ('description', models.TextField(blank=True, help_text='name of this event', null=True)),
                ('date_time', models.DateTimeField()),
                ('duration', models.IntegerField(blank=True, help_text='planned duration of this event', null=True)),
                ('location', models.CharField(blank=True, help_text='location where this event is being hosted', max_length=128, null=True)),
            ],
        ),
    ]
