# Generated by Django 5.0.1 on 2024-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_event_created_at_event_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID field for tracking a unique external event', max_length=1024, null=True),
        ),
    ]
