# Generated by Django 5.0.1 on 2024-03-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID field for tracking a unique external event', max_length=1024, null=True),
        ),
    ]
