# Generated by Django 5.0.1 on 2024-05-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_tag_options_alter_techgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventbriteOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('eventbrite_id', models.CharField(max_length=256)),
                ('tech_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.techgroup')),
            ],
        ),
    ]
