# Generated by Django 5.0.1 on 2024-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_techgroup_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['approved_at'], name='web_event_approve_979e74_idx'),
        ),
    ]
