# Generated by Django 5.0.1 on 2024-08-15 06:46

import django.apps
from django.db import migrations
from django.utils import timezone


def migrate(apps: django.apps.registry.Apps, schema_editor) -> None:
    """Automatically approve all existing Events."""
    Event = apps.get_model("web", "Event")
    now = timezone.localtime()
    Event.objects.update(approved_at=now)


def reverse(apps, schema_editor) -> None:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_event_approved_at_event_web_event_approve_979e74_idx'),
    ]

    operations = [
        migrations.RunPython(migrate, reverse)
    ]
