# Generated by Django 5.0.8 on 2024-09-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_event_image_techgroup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbriteorganization',
            name='eventbrite_id',
        ),
    ]
