on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Check Django
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: Check Django
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          args: "linters check_django"
          version: "0.12.6"
