on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Lint using Ruff
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
      - name: Lint using Ruff
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          args: "linters check"
          version: "0.12.6"
